- name: 문서
  color: "1d76db"
  description: 문서 및 주석 수정

- name: 기능
  color: "2ecc40"
  description: 새로운 기능 개발

- name: 리뷰 요청
  color: "17a2b8"
  description: 리뷰 준비 완료

- name: 개선
  color: "27ae60"
  description: 기존 기능 개선

- name: 환경 설정
  color: "bfbfbf"
  description: 빌드, 설정, 의존성 관리

- name: 스타일
  color: "a569bd"
  description: 코드 스타일, 포맷팅

- name: 테스트
  color: "ffb300"
  description: 테스트 코드 관련

- name: 리팩토링
  color: "f39c12"
  description: 코드 구조 개선 (기능 변화 없음)

- name: 버그 수정
  color: "e74c3c"
  description: 버그 해결

- name: 의존성 관리
  color: "6f42c1"
  description: 라이브러리 및 패키지 변경
